apiVersion: batch/v1
kind: CronJob
metadata:
  name: top-plays-cron-production
spec:
  # run at a 15min offset from new-cron (which runs on the 0, 30, etc.)
  schedule: "15-59/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: top-plays-cron-production
            image: osuakatsuki/top-plays-cron:latest
            imagePullPolicy: Always
            command:
              - ./scripts/bootstrap.sh
            env:
              - name: KUBERNETES
                value: 'true'
              - name: PULL_SECRETS_FROM_VAULT
                value: '1'
              - name: VAULT_ADDR
                valueFrom:
                  secretKeyRef:
                    name: vault
                    key: address
              - name: VAULT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: vault
                    key: token
              - name: APP_ENV
                value: production # TODO
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: osuakatsuki-registry-secret
